# Generated by Django 4.1.3 on 2022-11-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("location", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="city",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="governorate",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="governorate",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
