# Generated by Django 4.1.3 on 2022-11-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0002_city_title_ar_city_title_en_governorate_title_ar_and_more")
    ]

    operations = [migrations.RemoveField(model_name="city", name="user")]
