# Generated by Django 4.1.4 on 2022-12-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("location", "0007_address_zip_code")]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="address_en",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
