# Generated by Django 4.1.3 on 2022-11-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, max_length=512, null=True, upload_to="images/%Y/%m/%d"
            ),
        )
    ]
