# Generated by Django 4.1.3 on 2022-11-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0003_phone")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/profile/%Y/%m/%d"
            ),
        )
    ]
