# Generated by Django 4.1.3 on 2022-11-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0002_attribut_product_alter_category_title_and_more")]

    operations = [
        migrations.AddField(
            model_name="attribut",
            name="title_ar",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="attribut",
            name="title_en",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
