# Generated by Django 4.1.3 on 2022-11-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0003_attribut_title_ar_attribut_title_en")]

    operations = [
        migrations.AddField(
            model_name="attributdetails",
            name="value_ar",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="attributdetails",
            name="value_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_ar",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="title_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ar",
            field=models.CharField(max_length=192, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(max_length=192, null=True),
        ),
    ]
