# Generated by Django 4.1.3 on 2022-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0008_productorder")]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="attribut",
            field=models.JSONField(blank=True, null=True),
        )
    ]
