# Generated by Django 4.1.3 on 2022-11-18 23:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("store", "0009_alter_productorder_attribut")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, populate_from="title", unique=True
            ),
            preserve_default=False,
        )
    ]
