# Generated by Django 4.1.3 on 2022-11-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0011_alter_category_slug")]

    operations = [
        migrations.AddField(
            model_name="shippingcompany",
            name="name_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shippingcompany",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
