# Generated by Django 4.1.3 on 2022-11-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0014_alter_productattribut_attribut")]

    operations = [
        migrations.AddField(
            model_name="product", name="active", field=models.BooleanField(default=True)
        )
    ]
