# Generated by Django 4.1.3 on 2022-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0015_product_active")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amount",
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        )
    ]
