# Generated by Django 4.1.3 on 2022-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0017_bazarlog")]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="request_type",
            field=models.CharField(
                choices=[("d", "d"), ("m", "m")], default="d", max_length=1
            ),
        )
    ]
