# Generated by Django 3.2 on 2022-11-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20221124_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='product',
        ),
        migrations.AddField(
            model_name='orderlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='store.productorder'),
        ),
    ]
