# Generated by Django 3.2 on 2022-11-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20221124_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='type',
        ),
        migrations.AddField(
            model_name='orderlog',
            name='mozaeda',
            field=models.BooleanField(default=False),
        ),
    ]
