# Generated by Django 4.1.3 on 2022-11-26 17:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0022_auto_20221124_1438")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="current_price",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="increase_amount",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="min_price",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
    ]
