# Generated by Django 4.1.3 on 2022-11-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0023_alter_product_current_price_and_more")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                choices=[
                    ("bazar", "Bazar"),
                    ("direct", "Direct"),
                    ("mozaeda", "Mozaeda"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title_ar",
            field=models.CharField(
                choices=[
                    ("bazar", "Bazar"),
                    ("direct", "Direct"),
                    ("mozaeda", "Mozaeda"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title_en",
            field=models.CharField(
                choices=[
                    ("bazar", "Bazar"),
                    ("direct", "Direct"),
                    ("mozaeda", "Mozaeda"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
