# Generated by Django 4.1.3 on 2022-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0025_remove_category_title_ar_remove_category_title_en")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="current_price",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        )
    ]
