# Generated by Django 4.1.3 on 2022-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0026_alter_product_current_price")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
