# Generated by Django 3.2.1 on 2022-12-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='product',
        ),
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
    ]
