# Generated by Django 3.2.1 on 2022-12-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_media_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='store.order'),
        ),
    ]
