# Generated by Django 3.2.1 on 2022-12-07 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_address_user'),
        ('store', '0033_product_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='location.address'),
        ),
    ]
