# Generated by Django 3.2.1 on 2022-12-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_product_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('s', 'Shipping'), ('c', 'Cancled'), ('d', 'Done')], default='p', max_length=1),
        ),
    ]
