# Generated by Django 3.2.1 on 2022-12-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reject_message',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
