# Generated by Django 3.2.1 on 2022-12-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ar',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
