# Generated by Django 4.1.3 on 2022-12-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0041_brand")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=1),
        )
    ]
