# Generated by Django 4.1.3 on 2022-12-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0042_product_stock")]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="title_ar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
