# Generated by Django 4.1.3 on 2022-12-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0007_address_zip_code"),
        ("store", "0043_brand_title_ar_brand_title_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="location.address",
            ),
        )
    ]
