# Generated by Django 4.1.3 on 2022-12-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("store", "0046_slider_title_ar_slider_title_en_and_more")]

    operations = [
        migrations.RemoveField(model_name="slider", name="media"),
        migrations.AddField(
            model_name="slidermedia",
            name="slider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media",
                to="store.slider",
            ),
        ),
    ]
