# Generated by Django 4.1.3 on 2022-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0047_remove_slider_media_slidermedia_slider")]

    operations = [
        migrations.AddField(
            model_name="slider", name="content_ar", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="slider", name="content_en", field=models.TextField(null=True)
        ),
    ]
