# Generated by Django 4.1.3 on 2022-12-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("store", "0048_slider_content_ar_slider_content_en")]

    operations = [
        migrations.RemoveField(model_name="slidermedia", name="description"),
        migrations.RemoveField(model_name="slidermedia", name="description_ar"),
        migrations.RemoveField(model_name="slidermedia", name="description_en"),
        migrations.RemoveField(model_name="slidermedia", name="title"),
        migrations.RemoveField(model_name="slidermedia", name="title_ar"),
        migrations.RemoveField(model_name="slidermedia", name="title_en"),
    ]
