# Generated by Django 4.1.3 on 2022-12-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("store", "0049_remove_slidermedia_description_and_more")]

    operations = [
        migrations.AddField(
            model_name="media",
            name="alt",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="attribut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media",
                to="store.attribut",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="value",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
