# Generated by Django 4.1.3 on 2022-12-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0052_rename_tex_shippingcompany_tax")]

    operations = [
        migrations.AlterField(
            model_name="shippingcompany",
            name="tax",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        )
    ]
