# Generated by Django 4.1.4 on 2022-12-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("store", "0054_alter_shippingcompany_cost")]

    operations = [
        migrations.CreateModel(
            name="AuctionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direct", models.BooleanField(default=False)),
                (
                    "current_payment",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "auction_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auction_orders",
                        to="store.product",
                    ),
                ),
                (
                    "order_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auction_orders",
                        to="store.order",
                    ),
                ),
            ],
        )
    ]
