# Generated by Django 4.1.4 on 2022-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0057_product_discount_product_sale")]

    operations = [
        migrations.RemoveField(model_name="media", name="attribut"),
        migrations.AddField(
            model_name="media",
            name="attributes",
            field=models.ManyToManyField(
                null=True, related_name="medias", to="store.attribut"
            ),
        ),
    ]
