# Generated by Django 4.1.4 on 2022-12-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0058_remove_media_attribut_media_attributes")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        )
    ]
