# Generated by Django 4.1.4 on 2022-12-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0060_alter_product_discount")]

    operations = [
        migrations.CreateModel(
            name="AttributValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=128)),
                ("value_en", models.CharField(max_length=128, null=True)),
                ("value_ar", models.CharField(max_length=128, null=True)),
            ],
        )
    ]
