# Generated by Django 4.1.4 on 2022-12-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0062_remove_productattribut_value_ar_and_more")]

    operations = [
        migrations.RemoveField(model_name="productattribut", name="value"),
        migrations.AddField(
            model_name="productattribut",
            name="values",
            field=models.ManyToManyField(
                related_name="product_attrs", to="store.attributvalue"
            ),
        ),
    ]
