# Generated by Django 4.1.4 on 2022-12-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0064_alter_media_attributes")]

    operations = [
        migrations.RenameField(
            model_name="slider", old_name="content", new_name="description"
        ),
        migrations.RenameField(
            model_name="slider", old_name="content_ar", new_name="description_ar"
        ),
        migrations.RenameField(
            model_name="slider", old_name="content_en", new_name="description_en"
        ),
        migrations.AddField(
            model_name="slider",
            name="type",
            field=models.CharField(
                choices=[
                    ("auction", "Auction"),
                    ("shop", "Shop"),
                    ("direct", "Direct"),
                ],
                default="shop",
                max_length=10,
            ),
        ),
    ]
