# Generated by Django 4.1.4 on 2022-12-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("store", "0067_alter_slider_type")]

    operations = [
        migrations.RenameField(
            model_name="slider", old_name="type", new_name="slider_type"
        )
    ]
