# Generated by Django 4.1.4 on 2022-12-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("store", "0068_rename_type_slider_slider_type")]

    operations = [
        migrations.RemoveField(model_name="slidermedia", name="slider"),
        migrations.AddField(
            model_name="slider",
            name="slider_media",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.slidermedia",
            ),
        ),
    ]
