# Generated by Django 4.1.4 on 2022-12-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("store", "0069_remove_slidermedia_slider_slider_slider_media")]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="slider",
            name="page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sliders",
                to="store.page",
            ),
        ),
    ]
