# Generated by Django 4.1.4 on 2022-12-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0070_page_slider_page")]

    operations = [
        migrations.RemoveField(model_name="slider", name="slider_type"),
        migrations.AddField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[("auction", "Auction"), ("shop", "Shop"), ("bazar", "Bazar")],
                default="shop",
                max_length=10,
            ),
        ),
    ]
