# Generated by Django 4.1.4 on 2022-12-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("store", "0072_productviewers")]

    operations = [
        migrations.AlterField(
            model_name="productviewers",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="store.product",
            ),
        )
    ]
