# Generated by Django 4.1.4 on 2022-12-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0073_alter_productviewers_product")]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("auction", "Auction"),
                    ("shop", "Shop"),
                    ("bazar", "Bazar"),
                    ("home", "Home"),
                ],
                default="shop",
                max_length=10,
            ),
        )
    ]
