# Generated by Django 4.1.4 on 2022-12-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0074_alter_page_page_type")]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="images/logo/")),
            ],
        )
    ]
