# Generated by Django 4.1.4 on 2022-12-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0075_logo")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="code",
            field=models.CharField(
                choices=[("auction", "Auction"), ("shop", "Shop"), ("bazar", "Bazar")],
                max_length=12,
                null=True,
            ),
        )
    ]
