# Generated by Django 4.1.4 on 2022-12-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0077_alter_page_page_type")]

    operations = [
        migrations.AddField(
            model_name="page",
            name="about_ar",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="about_en",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="page", name="about", field=models.CharField(max_length=512)
        ),
    ]
