# Generated by Django 4.1.4 on 2022-12-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0078_page_about_ar_page_about_en_alter_page_about")]

    operations = [
        migrations.AddField(
            model_name="page",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/page/%Y/%m/%d"
            ),
        )
    ]
