# Generated by Django 4.1.4 on 2022-12-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0080_alter_page_page_type")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(
                choices=[
                    ("auctions", "Auction"),
                    ("shops", "Shop"),
                    ("bazaar", "Bazar"),
                ],
                max_length=12,
                null=True,
            ),
        )
    ]
