# Generated by Django 3.2.1 on 2022-12-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0081_alter_category_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlog',
            old_name='mozaeda',
            new_name='auctions',
        ),
    ]
