# Generated by Django 4.1.4 on 2022-12-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0084_product_brand")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/category/banners/%Y/%m/%d"
            ),
        )
    ]
