# Generated by Django 4.1.4 on 2022-12-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0085_category_banner")]

    operations = [
        migrations.AlterField(
            model_name="logo",
            name="file",
            field=models.FileField(upload_to="images/logo/%Y/%m/%d"),
        )
    ]
