# Generated by Django 4.1.4 on 2022-12-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0086_alter_logo_file")]

    operations = [
        migrations.AddField(
            model_name="media", name="is_logo", field=models.BooleanField(default=False)
        )
    ]
