# Generated by Django 4.1.4 on 2022-12-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0087_media_is_logo")]

    operations = [
        migrations.AlterField(
            model_name="attribut",
            name="code",
            field=models.CharField(max_length=40, null=True),
        )
    ]
