# Generated by Django 4.1.4 on 2022-12-25 18:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0088_alter_attribut_code")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="current_price",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="increase_amount",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
