# Generated by Django 4.1.4 on 2022-12-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0089_alter_product_current_price_alter_product_end_time_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auctions", "Auction"),
                    ("shops", "Shop"),
                    ("bazaar", "Bazar"),
                ],
                max_length=12,
                null=True,
            ),
        )
    ]
