# Generated by Django 4.1.4 on 2023-01-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("store", "0090_alter_category_code")]

    operations = [
        migrations.RemoveField(model_name="auctionorder", name="order_product")
    ]
