# Generated by Django 4.1.4 on 2023-01-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0095_remove_auctionorder_address_product_auction")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="auction_success",
            field=models.BooleanField(default=False),
        )
    ]
