# Generated by Django 4.1.4 on 2023-01-14 11:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [("store", "0096_product_auction_success")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="lang",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="lat",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="zip",
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
