# Generated by Django 4.1.4 on 2023-01-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0097_order_lang_order_lat_order_phone_order_zip_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="attributdetails",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attrs",
                to="store.order",
            ),
        )
    ]
