# Generated by Django 4.1.4 on 2023-01-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("store", "0098_attributdetails_order")]

    operations = [
        migrations.AlterField(
            model_name="attributdetails",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attrs",
                to="store.order",
            ),
        )
    ]
