# Generated by Django 4.1.4 on 2023-01-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("store", "0100_alter_attributdetails_order")]

    operations = [migrations.RemoveField(model_name="media", name="value")]
