# Generated by Django 4.1.4 on 2023-01-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("store", "0101_remove_media_value")]

    operations = [
        migrations.AddField(
            model_name="media",
            name="value",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media",
                to="store.attributdetails",
            ),
        )
    ]
