# Generated by Django 4.1.4 on 2023-01-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("store", "0102_media_value")]

    operations = [migrations.RemoveField(model_name="product", name="auction")]
