# Generated by Django 4.1.4 on 2023-01-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("store", "0104_product_auction_viewrs")]

    operations = [
        migrations.RemoveField(model_name="productattribut", name="values"),
        migrations.AlterField(
            model_name="productattribut",
            name="attribut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_attrs",
                to="store.attribut",
            ),
        ),
        migrations.AlterField(
            model_name="productattribut",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attrs",
                to="store.product",
            ),
        ),
    ]
