# Generated by Django 4.1.4 on 2023-01-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0104_product_auction_viewrs")]

    operations = [
        migrations.AlterField(
            model_name="productattribut",
            name="values",
            field=models.ManyToManyField(
                related_name="product_attrs", to="store.attributdetails"
            ),
        )
    ]
