# Generated by Django 4.1.4 on 2023-01-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0105_remove_productattribut_values_and_more")]

    operations = [
        migrations.AddField(
            model_name="productattribut",
            name="values",
            field=models.ManyToManyField(
                related_name="product_attrs", to="store.attributdetails"
            ),
        )
    ]
