# Generated by Django 4.1.4 on 2023-01-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0107_alter_order_status")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipping"),
                    ("cancled", "Cancled"),
                ],
                default="pending",
                max_length=17,
            ),
        )
    ]
