# Generated by Django 4.1.4 on 2023-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0108_alter_order_status")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("p", "Pending"), ("s", "Shipping"), ("c", "Cancled")],
                default="p",
                max_length=17,
            ),
        )
    ]
