# Generated by Django 4.1.4 on 2023-01-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0110_auto_20230121_1813")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("p", "Pending"),
                    ("s", "Shipping"),
                    ("c", "Cancled"),
                    ("a", "Accepted"),
                ],
                default="p",
                max_length=17,
            ),
        )
    ]
