# Generated by Django 4.1.3 on 2022-11-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("general", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="contactsettings",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactsettings",
            name="facebook",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="contactsettings",
            name="gmail",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="contactsettings",
            name="instagram",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="contactsettings",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contactsettings",
            name="phone",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="contactsettings",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
