# Generated by Django 4.1.3 on 2022-12-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("general", "0004_auto_20221207_2018")]

    operations = [
        migrations.AddField(
            model_name="contactsettings",
            name="fax",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="youtube",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
