# Generated by Django 4.1.4 on 2022-12-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0068_rename_type_slider_slider_type"),
        ("general", "0005_contactsettings_fax_contactsettings_youtube"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField()),
                (
                    "slider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page",
                        to="store.slider",
                    ),
                ),
            ],
        )
    ]
