# Generated by Django 4.1.4 on 2022-12-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("general", "0006_page")]

    operations = [migrations.RemoveField(model_name="page", name="slider")]
