# Generated by Django 4.1.4 on 2022-12-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("general", "0007_remove_page_slider")]

    operations = [migrations.DeleteModel(name="Page")]
