# Generated by Django 4.1.3 on 2022-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0006_review")]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="type",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WHATSAPP"),
                    ("mobile", "MOBILE"),
                    ("fax", "FAX"),
                    ("work", "WORK"),
                ],
                max_length=16,
            ),
        )
    ]
