# Generated by Django 4.1.4 on 2022-12-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("authentication", "0010_review_rate")]

    operations = [
        migrations.AddField(
            model_name="review",
            name="createdat",
            field=models.DateTimeField(auto_now_add=True, null=True),
        )
    ]
